plugins {
    id 'java'
}

group = 'com.herepunchy'
version = '1.1.0'

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

repositories {
    mavenCentral()
    maven { url = 'https://repo.papermc.io/repository/maven-public/' }
}

dependencies {
    compileOnly 'io.papermc.paper:paper-api:1.21.4-R0.1-SNAPSHOT'
    compileOnly 'dev.aurelium:auraskills-api-bukkit:2.2.4'
    compileOnly files('../HereRolePlay/build/libs/HereRolePlay-1.0.0.jar')
}

processResources {
    def props = [version: version]
    inputs.properties props
    filteringCharset 'UTF-8'
    filesMatching('plugin.yml') {
        expand props
    }
}

jar {
    archiveBaseName = 'HerePunchy'
    archiveVersion = version
}
